service.upstream:
  - delhi_dc:
      - host: service.delhi.dummyorg.com
        weight: 100
  - mumbai_dc:
      - host: service-01.mumbai.dummyorg.com
        weight: 50
      - host: service-02.mumbai.dummyorg.com
        weight: 50

