---
_format_version: '3.0'
services:
- name: admin-portal
  host: admin.upstream
  port: 443
  protocol: https
  connect_timeout: 30000
  tags:
  - internal
  - admin
  - banking
upstreams:
- name: admin.upstream
  targets:
  - target: admin.delhi.bank.internal:443
    weight: 100
  hash_on: none
  hash_fallback: none
  hash_on_cookie_path: "/"
  slots: 10000
  healthchecks:
    passive:
      type: http
      unhealthy:
        http_statuses:
        - 429
        - 500
        - 503
        http_failures: 5
        interval: 0
      healthy:
        http_statuses:
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 226
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 306
        - 307
        - 308
        successes: 0
routes:
- name: admin-dashboard
  hosts:
  - admin.bank.internal
  paths:
  - "/dashboard"
  - "/api/admin"
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  service:
    name: admin-portal
