#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)

begin
  require 'pry-byebug' if ENV['GOJIRA_ENV'] == 'debug'
rescue LoadError
  # do nothing
end

require 'gojira'

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

Gojira::CLI.start(ARGV)
